apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: qa 
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: akintolacr.azurecr.io/portfolio-app:latest
          ports:
            - containerPort: 8045

      nodeSelector:
        app: system-apps

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-clusterip-service
  namespace: qa  
  labels:
    app: portfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 8045
