# QA Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: qa
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: akintolacr.azurecr.io/flask:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---

# QA Service
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: qa
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
