# QA Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  namespace: qa
  labels:
    app: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: akintolacr.azurecr.io/testapp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---

# QA Service
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
  namespace: qa
spec:
  selector:
    app: dotnetapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
